SimulationAerolinea/config/routes.rb
Rails.application.routes.draw do
  
  resources :airplanes
  resources :passengers
  resources :pilots
  resources :cities
  resources :flights
  resources :routes

  get 'flights/:id/buy_ticket/:flight' => 'passengers#buy_ticket', as: "buy_ticket"

end

SimulationAerolinea/app/models/flight.rb
class Flight < ActiveRecord::Base

	belongs_to :route
	belongs_to :pilot
	belongs_to :airplane
	has_and_belongs_to_many :passengers
	
	validates :route_id, :pilot_id, :airplane_id, presence: true

end

SimulationAerolinea/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:route_id, :airplane_id, :pilot_id, :date, :price)
    end
end

SimulationAerolinea/app/helpers/flights_helper.rb
module FlightsHelper
end

SimulationAerolinea/app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.select :route_id, Route.all.collect {|r| ["#{r.city_o.name_city}-#{r.city_y.name_city}", r.id]}%>
  </div>
  <div class="field">
    <%= f.label :airplane_id %><br>
    <%= f.select :airplane_id, Airplane.all.collect {|a| [a.reference, a.id]} %>
  </div>
  <div class="field">
    <%= f.label :pilot_id %><br>
    <%= f.select :pilot_id, Pilot.all.collect {|p| ["#{p.identificacion}-#{p.name}-#{p.lastname}", p.id]}%>
  </div>
  <div class="field">
    <%= f.label :date, "Fecha de vuelo" %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SimulationAerolinea/app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

SimulationAerolinea/app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de vuelos</h1>

<table>
  <thead>
    <tr>
      <th>Route</th>
      <th>Airplane</th>
      <th>Pilot</th>
      <th>Date</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.route.define_route%></td>
        <td><%= flight.airplane.reference %></td>
        <td><%= flight.pilot.identificacion %></td>
        <td><%= flight.date.strftime("%B %d %Y %H:%M:%S") %></td>
        <td><%= number_to_currency flight.price %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Comprar', buy_ticket_path(flight: flight.id, id: 1) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ingresar nuevo vuelo', new_flight_path %>

SimulationAerolinea/app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

SimulationAerolinea/app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route:</strong>
  <%= @flight.route_id %>
</p>

<p>
  <strong>Airplane:</strong>
  <%= @flight.airplane_id %>
</p>

<p>
  <strong>Pilot:</strong>
  <%= @flight.pilot_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flight.price %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>