SimulationAerolinea/config/routes.rb
Rails.application.routes.draw do
  
  resources :airplanes
  resources :passengers
  resources :pilots
  resources :cities
  resources :flights
  resources :routes

  get 'flights/:id/buy_ticket/:flight' => 'passengers#buy_ticket', as: "buy_ticket"

end

SimulationAerolinea/app/models/pilot.rb
class Pilot < ActiveRecord::Base
	has_many :flights
	
	def complete
		"#{identificacion} #{name} #{lastname}"
	end

end

SimulationAerolinea/app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: [:show, :edit, :update, :destroy]

  # GET /pilots
  # GET /pilots.json
  def index
    @pilots = Pilot.all
  end

  # GET /pilots/1
  # GET /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots
  # POST /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: 'Pilot was successfully created.' }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1
  # PATCH/PUT /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: 'Pilot was successfully updated.' }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url, notice: 'Pilot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pilot_params
      params.require(:pilot).permit(:name, :lastname, :identificacion, :edad)
    end
end

SimulationAerolinea/app/helpers/pilots_helper.rb
module PilotsHelper
end

SimulationAerolinea/app/views/pilots/_form.html.erb
<%= form_for(@pilot) do |f| %>
  <% if @pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
      <% @pilot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :identificacion %><br>
    <%= f.number_field :identificacion %>
  </div>
  <div class="field">
    <%= f.label :edad %><br>
    <%= f.number_field :edad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SimulationAerolinea/app/views/pilots/edit.html.erb
<h1>Editing Pilot</h1>

<%= render 'form' %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %>

SimulationAerolinea/app/views/pilots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Pilotos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Identificacion</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pilots.each do |pilot| %>
      <tr>
        <td><%= pilot.name %></td>
        <td><%= pilot.lastname %></td>
        <td><%= pilot.identificacion %></td>
        <td><%= pilot.edad %></td>
        <td><%= link_to 'Show', pilot %></td>
        <td><%= link_to 'Edit', edit_pilot_path(pilot) %></td>
        <td><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ingresar Nuevo Piloto', new_pilot_path %>

SimulationAerolinea/app/views/pilots/new.html.erb
<h1>New Pilot</h1>

<%= render 'form' %>

<%= link_to 'Back', pilots_path %>

SimulationAerolinea/app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pilot.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @pilot.lastname %>
</p>

<p>
  <strong>Identificacion:</strong>
  <%= @pilot.identificacion %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @pilot.edad %>
</p>

<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>