SimulationAerolinea/config/routes.rb
Rails.application.routes.draw do
  
  resources :airplanes
  resources :passengers
  resources :pilots
  resources :cities
  resources :flights
  resources :routes

  get 'flights/:id/buy_ticket/:flight' => 'passengers#buy_ticket', as: "buy_ticket"

end

SimulationAerolinea/app/models/route.rb
class Route < ActiveRecord::Base
	belongs_to :city_o, class_name: 'City', foreign_key: 'city_o_id'
	belongs_to :city_y, class_name: 'City', foreign_key: 'city_y_id'
	has_many :flights

#validates :city_y_id, :city_o_id, presence: true
#validates :city_y_id, :city_o_id, numericality: {only_integer: true}

validate :city_o_city_y

def city_o_city_y
	if self.city_y_id == self.city_o_id
		errors.add(:city_y_id, "La ciudad destino debe ser diferente a la ciudad origen")
	end
end



def define_route
	"#{self.city_o.name_city}" "-" "#{self.city_y.name_city}"
end

end

SimulationAerolinea/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:city_o_id, :city_y_id)
    end
end

SimulationAerolinea/app/helpers/routes_helper.rb
module RoutesHelper

	def boton_like
		link_to 'Google', 'http://google.com'
	end

end

SimulationAerolinea/app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city_o_id,"Ciudad de origen:"%><br>
    <%= f.select :city_o_id, City.all.collect {|c| [c.name_city, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :city_y_id, "Ciudad de destino:"%><br>
    <%= f.select :city_y_id, City.all.collect {|c| [c.name_city, c.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SimulationAerolinea/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

SimulationAerolinea/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Rutas</h1>

<table>
  <thead>
    <tr>
      <th>Ciudad de origen</th>
      <th>Ciudad de destino</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.city_o.name_city %></td>
        <td><%= route.city_y.name_city %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Ruta', new_route_path %>

SimulationAerolinea/app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

SimulationAerolinea/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Ciudad origen:</h2>
  <span><%= @route.city_o.name_city %></span>
<span><%= @route.city_o.country %></span>
</p>

<p>
  <h2>Ciudad destino:</h2>
  <span><%= @route.city_y.name_city %></span>
 <span><%= @route.city_y.country %></span> 
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>